//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.13 at 07:43:55 PM NZST 
//


package nz.co.iswe.mediamanager.media.nfo.xml.movie;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nz.co.iswe.mediamanager.media.nfo.xml.movie package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Genre_QNAME = new QName("", "genre");
    private final static QName _Trailer_QNAME = new QName("", "trailer");
    private final static QName _Set_QNAME = new QName("", "set");
    private final static QName _Votes_QNAME = new QName("", "votes");
    private final static QName _Credits_QNAME = new QName("", "credits");
    private final static QName _Runtime_QNAME = new QName("", "runtime");
    private final static QName _Codec_QNAME = new QName("", "codec");
    private final static QName _Filenameandpath_QNAME = new QName("", "filenameandpath");
    private final static QName _Outline_QNAME = new QName("", "outline");
    private final static QName _Plot_QNAME = new QName("", "plot");
    private final static QName _Watched_QNAME = new QName("", "watched");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Title_QNAME = new QName("", "title");
    private final static QName _Height_QNAME = new QName("", "height");
    private final static QName _Name_QNAME = new QName("", "name");
    private final static QName _Role_QNAME = new QName("", "role");
    private final static QName _Year_QNAME = new QName("", "year");
    private final static QName _Sorttitle_QNAME = new QName("", "sorttitle");
    private final static QName _Width_QNAME = new QName("", "width");
    private final static QName _Top250_QNAME = new QName("", "top250");
    private final static QName _Channels_QNAME = new QName("", "channels");
    private final static QName _Playcount_QNAME = new QName("", "playcount");
    private final static QName _Director_QNAME = new QName("", "director");
    private final static QName _Mpaa_QNAME = new QName("", "mpaa");
    private final static QName _Aspect_QNAME = new QName("", "aspect");
    private final static QName _Language_QNAME = new QName("", "language");
    private final static QName _Rating_QNAME = new QName("", "rating");
    private final static QName _Thumb_QNAME = new QName("", "thumb");
    private final static QName _Originaltitle_QNAME = new QName("", "originaltitle");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nz.co.iswe.mediamanager.media.nfo.xml.movie
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MediaManager }
     * 
     */
    public MediaManager createMediaManager() {
        return new MediaManager();
    }

    /**
     * Create an instance of {@link Fileinfo }
     * 
     */
    public Fileinfo createFileinfo() {
        return new Fileinfo();
    }

    /**
     * Create an instance of {@link Streamdetails }
     * 
     */
    public Streamdetails createStreamdetails() {
        return new Streamdetails();
    }

    /**
     * Create an instance of {@link Video }
     * 
     */
    public Video createVideo() {
        return new Video();
    }

    /**
     * Create an instance of {@link Audio }
     * 
     */
    public Audio createAudio() {
        return new Audio();
    }

    /**
     * Create an instance of {@link Subtitle }
     * 
     */
    public Subtitle createSubtitle() {
        return new Subtitle();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Movie }
     * 
     */
    public Movie createMovie() {
        return new Movie();
    }

    /**
     * Create an instance of {@link Tagline }
     * 
     */
    public Tagline createTagline() {
        return new Tagline();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "genre")
    public JAXBElement<String> createGenre(String value) {
        return new JAXBElement<String>(_Genre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trailer")
    public JAXBElement<String> createTrailer(String value) {
        return new JAXBElement<String>(_Trailer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "set")
    public JAXBElement<String> createSet(String value) {
        return new JAXBElement<String>(_Set_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "votes")
    public JAXBElement<Integer> createVotes(Integer value) {
        return new JAXBElement<Integer>(_Votes_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "credits")
    public JAXBElement<String> createCredits(String value) {
        return new JAXBElement<String>(_Credits_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "runtime")
    public JAXBElement<String> createRuntime(String value) {
        return new JAXBElement<String>(_Runtime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "codec")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCodec(String value) {
        return new JAXBElement<String>(_Codec_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filenameandpath")
    public JAXBElement<String> createFilenameandpath(String value) {
        return new JAXBElement<String>(_Filenameandpath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "outline")
    public JAXBElement<String> createOutline(String value) {
        return new JAXBElement<String>(_Outline_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "plot")
    public JAXBElement<String> createPlot(String value) {
        return new JAXBElement<String>(_Plot_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "watched")
    public JAXBElement<Boolean> createWatched(Boolean value) {
        return new JAXBElement<Boolean>(_Watched_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createId(String value) {
        return new JAXBElement<String>(_Id_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "title")
    public JAXBElement<String> createTitle(String value) {
        return new JAXBElement<String>(_Title_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "height")
    public JAXBElement<Integer> createHeight(Integer value) {
        return new JAXBElement<Integer>(_Height_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "role")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRole(String value) {
        return new JAXBElement<String>(_Role_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "year")
    public JAXBElement<Integer> createYear(Integer value) {
        return new JAXBElement<Integer>(_Year_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sorttitle")
    public JAXBElement<String> createSorttitle(String value) {
        return new JAXBElement<String>(_Sorttitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "width")
    public JAXBElement<Integer> createWidth(Integer value) {
        return new JAXBElement<Integer>(_Width_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "top250")
    public JAXBElement<Integer> createTop250(Integer value) {
        return new JAXBElement<Integer>(_Top250_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "channels")
    public JAXBElement<Integer> createChannels(Integer value) {
        return new JAXBElement<Integer>(_Channels_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "playcount")
    public JAXBElement<Integer> createPlaycount(Integer value) {
        return new JAXBElement<Integer>(_Playcount_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "director")
    public JAXBElement<String> createDirector(String value) {
        return new JAXBElement<String>(_Director_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mpaa")
    public JAXBElement<String> createMpaa(String value) {
        return new JAXBElement<String>(_Mpaa_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "aspect")
    public JAXBElement<BigDecimal> createAspect(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Aspect_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createLanguage(String value) {
        return new JAXBElement<String>(_Language_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "rating")
    public JAXBElement<String> createRating(String value) {
        return new JAXBElement<String>(_Rating_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "thumb")
    public JAXBElement<String> createThumb(String value) {
        return new JAXBElement<String>(_Thumb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "originaltitle")
    public JAXBElement<String> createOriginaltitle(String value) {
        return new JAXBElement<String>(_Originaltitle_QNAME, String.class, null, value);
    }

}
